# Dependabot configuration for automated dependency updates
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # 📦 NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Security updates are prioritized
    open-pull-requests-limit: 10
    target-branch: "main"
    reviewers:
      - "docdyhr"
    assignees:
      - "docdyhr"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "security"
    allow:
      - dependency-type: "all"
    # Group related updates together
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "@modelcontextprotocol/*"
          - "axios"
          - "express*"
          - "zod*"
        exclude-patterns:
          - "@types/*"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "typescript*"
          - "vitest*"
          - "@typescript-eslint/*"
      wordpress-packages:
        patterns:
          - "wordpress*"
          - "@wordpress/*"
    # Rebase strategy for conflicts
    rebase-strategy: "auto"
    # Enable security advisories
    insecure-external-code-execution: "deny"

  # 🔧 GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "main"
    reviewers:
      - "docdyhr"
    assignees:
      - "docdyhr"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    groups:
      github-actions:
        patterns:
          - "*"

  # 🐳 Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    target-branch: "main"
    reviewers:
      - "docdyhr"
    assignees:
      - "docdyhr"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"

# Security updates are automatically created for all ecosystems
# and take priority over the schedule defined above