# Gitleaks configuration file  
title = "gitleaks config for mcp-wordpress"

[extend]
# useDefault will extend the base configuration with the default gitleaks config
useDefault = true

# Global allowlist - files and patterns to completely ignore
[allowlist]
# Files and directories to exclude from scanning
paths = [
    '''tests/.*''',
    '''.*\.test\.(js|ts)$''',
    '''.*\.spec\.(js|ts)$''',
    '''docs/.*\.md$''',
    '''README\.md''',
    '''\.github/ISSUE_TEMPLATE/.*''',
    '''dist/.*''',
    '''build/.*''',
    '''coverage/.*''',
    '''node_modules/.*''',
    '''package-lock\.json$''',
    '''yarn\.lock$''',
    '''\.vscode/.*''',
    '''\.idea/.*'''
]

# Regular expressions for content to ignore
regexes = [
    '''username:app_password''',
    '''username:password''',
    '''curl -u username:''',
    '''const encryptionKey = "test1234567890"''',
    '''WORDPRESS_APP_PASSWORD=xxxx\s+xxxx\s+xxxx\s+xxxx\s+xxxx\s+xxxx'''
]

# Specific commits to ignore (if needed)
commits = []