name: Legacy NPM Publish (Manual Release)

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run build
          npm test
          # Skip tool tests and health check in CI - they require real WordPress connectivity
          # npm run test:tools
          # npm run health
        env:
          # Test credentials for CI - tests will skip server instantiation if not available
          WORDPRESS_SITE_URL: https://test.example.com
          WORDPRESS_USERNAME: test_user
          WORDPRESS_APP_PASSWORD: test_password

      - name: Check ignore files
        run: npm run check:ignore

      - name: Verify package contents
        run: npm publish --dry-run

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}